### ISSUE TITLE
复制问题以及有问题的ps脚本

### ISSUE THREAD

**Issue by nomango** [lyy289065406/articles#1]
看了博主的一篇文章，https://exp-blog.com/container/wsl2-qian-yi-docker-cun-chu-wei-zhi/

遇到两个问题，一个是复制ps脚本的时候，换行会消失，只能停掉javascript再复制。

第二个是文章里贴的ps脚本有一点问题，`wsl --export`要指定一个已经存在的目录，否则会报错`系统找不到指定的路径`，但是并不会阻止脚本继续执行！！！！

于是就执行了`wsl --unregister`，于是在export失败的情况下，原来的发行版被删除了。。。。删除了！！！！我靠，心态直接炸裂

我真的要骂人了。。。。。。

**Comment by lyy289065406** [comment]
> 看了博主的一篇文章，https://exp-blog.com/container/wsl2-qian-yi-docker-cun-chu-wei-zhi/
> 
> 遇到两个问题，一个是复制ps脚本的时候，换行会消失，只能停掉javascript再复制。
> 
> 第二个是文章里贴的ps脚本有一点问题，`wsl --export`要指定一个已经存在的目录，否则会报错`系统找不到指定的路径`，但是并不会阻止脚本继续执行！！！！
> 
> 于是就执行了`wsl --unregister`，于是在export失败的情况下，原来的发行版被删除了。。。。删除了！！！！我靠，心态直接炸裂
> 
> 我真的要骂人了。。。。。。

最后有个下载链接你没看到？ 复制啥。。。

**Comment by nomango** [comment]
无所谓了，已经快忘了
